name: Build binary

on:
  workflow_dispatch
  # schedule:
  #  - cron: '5 5 * * *'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  ADHAMMER_ROOT_DIR: /tmp/adhammer
  ADHAMMER_BIN_NAME: adhammer
  ADHAMMER_REPO: https://github.com/icedracon/adhammer.git
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0
  CHOCO: choco install -y -r --no-progress

defaults:
  run:
    shell: bash

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      ADHAMMER_PREBUILT_LATEST_TAG: ${{ steps.release_latest_tag.outputs.ADHAMMER_PREBUILT_LATEST_TAG }}
      ADHAMMER_CURRENT_COMMIT_ID: ${{ steps.release_commit_id.outputs.ADHAMMER_CURRENT_COMMIT_ID }}
      ADHAMMER_VERSION: ${{ steps.release_version.outputs.ADHAMMER_VERSION }}
    
    steps:
      - name: Get latest release tag of this repo
        id: release_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/
          ADHAMMER_PREBUILT_LATEST_TAG=$(gh release list -R mycodedoesnotcompile2/adhammer_prebuilt_binaries --json tagName -L 1 --jq '.[].tagName' --exclude-drafts --exclude-pre-releases)
          echo "ADHAMMER_PREBUILT_LATEST_TAG=$ADHAMMER_PREBUILT_LATEST_TAG" >> $GITHUB_OUTPUT
          echo "ADHAMMER_PREBUILT_LATEST_TAG=$ADHAMMER_PREBUILT_LATEST_TAG" >> $GITHUB_ENV

      - name: Clone repo and check if there is a new and uncompiled yet version
        id: release_commit_id
        run: |
          cd /tmp/
          git clone --depth=1 "$ADHAMMER_REPO" "$ADHAMMER_BIN_NAME"

          cd "$ADHAMMER_ROOT_DIR"
          ADHAMMER_CURRENT_COMMIT_ID=$(git rev-parse --short HEAD)
          echo "ADHAMMER_CURRENT_COMMIT_ID=$ADHAMMER_CURRENT_COMMIT_ID" >> $GITHUB_ENV
          echo "ADHAMMER_CURRENT_COMMIT_ID=$ADHAMMER_CURRENT_COMMIT_ID" >> $GITHUB_OUTPUT

          # case: no new commit => abort the workflow
          if [[ $ADHAMMER_PREBUILT_LATEST_TAG == $ADHAMMER_CURRENT_COMMIT_ID ]]; then
            echo "[!] No new version to compile"
            exit 100
          fi

      - name: Get version
        id: release_version_cargo_get
        uses: nicolaiunrein/cargo-get@master
        with:
          subcommand: workspace.package.version
          options: --entry "$ADHAMMER_ROOT_DIR/Cargo.toml"

      - name: Set ADHAMMER_VERSION build variable
        id: release_version
        run: |
          ADHAMMER_VERSION=${{ steps.release_version_cargo_get.outputs.metadata }}
          echo "ADHAMMER_VERSION=$ADHAMMER_VERSION" >> $GITHUB_OUTPUT


  
  build:
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-unknown-linux-musl
            OS: ubuntu-latest
            
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-latest
            
          - TARGET: i686-unknown-linux-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-multilib

          - TARGET: i686-unknown-linux-musl
            OS: ubuntu-latest
            CC_COMPILER: cross
            CC_PKG: gcc-multilib
          
          - TARGET: aarch64-unknown-linux-musl
            OS: ubuntu-24.04-arm
            
          - TARGET: aarch64-unknown-linux-gnu
            OS: ubuntu-24.04-arm
          
          - TARGET: armv7-unknown-linux-musleabihf
            OS: ubuntu-latest
            CC_COMPILER: cross
          
          - TARGET: armv7-unknown-linux-gnueabihf
            OS: ubuntu-latest
            CC_PKG: crossbuild-essential-armhf

          - TARGET: arm-unknown-linux-musleabihf
            OS: ubuntu-latest
            CC_COMPILER: cross
          
          - TARGET: arm-unknown-linux-gnueabihf
            OS: ubuntu-latest
            CC_PKG: gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

          - TARGET: arm-unknown-linux-musleabi
            OS: ubuntu-latest
            CC_COMPILER: cross
          
          - TARGET: aarch64-apple-darwin
            OS: macos-latest

          - TARGET: x86_64-apple-darwin
            OS: macos-26-intel
          
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
            
          - TARGET: x86_64-pc-windows-gnu
            OS: windows-latest
            
          - TARGET: aarch64-pc-windows-msvc
            OS: windows-11-arm
          # ------------------------------

          - TARGET: x86_64-unknown-freebsd
            OS: ubuntu-latest
            CC_COMPILER: cross
            
          - TARGET: i586-unknown-linux-gnu
            OS: ubuntu-latest
            CC_COMPILER: cross

          - TARGET: i586-unknown-linux-musl
            OS: ubuntu-latest
            CC_COMPILER: cross

          - TARGET: i686-pc-windows-msvc
            OS: windows-latest

          - TARGET: i686-pc-windows-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-mingw-w64-i686

          - TARGET: riscv64gc-unknown-linux-gnu
            OS: ubuntu-latest
            CC_PKG: gcc-riscv64-linux-gnu

          - TARGET: riscv64gc-unknown-linux-musl
            OS: ubuntu-latest
            CC_COMPILER: cross

          - TARGET: powerpc64le-unknown-linux-gnu
            OS: ubuntu-latest
            CC_COMPILER: cross

          - TARGET: aarch64-linux-android
            OS: ubuntu-latest
            CC_COMPILER: cross
            
          - TARGET: armv7-linux-androideabi
            OS: ubuntu-latest
            CC_COMPILER: cross
            
          - TARGET: mips64el-unknown-linux-gnuabi64
            OS: ubuntu-latest
            CC_PKG: gcc-mips64el-linux-gnuabi64 g++-mips64el-linux-gnuabi64
           
          - TARGET: mips64el-unknown-linux-muslabi64
            OS: ubuntu-latest
            CC_COMPILER: cross
            
    runs-on: ${{ matrix.OS }}
    container:
      image: ${{ matrix.CONTAINER }}

    env:
      TARGET: ${{ matrix.TARGET }}
      OS: ${{ matrix.OS }}
      CONTAINER: ${{ matrix.CONTAINER }}
      CC_PKG: ${{ matrix.CC_PKG }}
      CC_COMPILER: ${{ matrix.CC_COMPILER }}
      CROSS_CONFIG: /tmp/cross.toml

      ADHAMMER_PREBUILT_LATEST_TAG: ${{ needs.checkout.outputs.ADHAMMER_PREBUILT_LATEST_TAG }}
      ADHAMMER_VERSION: ${{ needs.checkout.outputs.ADHAMMER_VERSION }}
      
    steps:
      - name: Clone repo
        run: |
          cd /tmp/
          git clone --depth=1 "$ADHAMMER_REPO" "$ADHAMMER_BIN_NAME"
      
      - name: Install and configure dependencies
        run: |
          if [[ $OS == windows* ]]; then
            $CHOCO wget
          fi
          
          if [[ $OS == ubuntu* ]]; then
            $APT update 
            #$APT install libssl-dev pkg-config
          fi

          # for musl builds
          if [[ $TARGET == *"-musl"* ]]; then
            $APT install musl-tools
          fi

          # for everything else
          if [[ -n "${CC_PKG:-}" ]]; then
            $APT install $CC_PKG
          fi

          # for arm targets
          if [[ $TARGET == "arm"* ]]; then
            cd "$ADHAMMER_ROOT_DIR"
            cargo install --force --locked bindgen-cli
          fi
          
          cargo install cross
          
          wget -nv "https://github.com/mycodedoesnotcompile2/rust_compile_config_files/raw/refs/heads/main/cross.toml" -O "$CROSS_CONFIG"
          wget -nv "https://github.com/mycodedoesnotcompile2/rust_compile_config_files/raw/refs/heads/main/config.toml" -O ~/.cargo/config.toml

      
      - name: Install rust target
        run: |
          if [[ $TARGET == "mips"* ]]; then
            rustup toolchain install nightly
            rustup component add rust-src --toolchain nightly
          else
            rustup target add $TARGET
          fi

      - name: Patch toml
        run: |
          if [[ $TARGET == *"-musl"* || $TARGET == "arm"* || $TARGET == "risc"* || $TARGET == "mips"* || $TARGET == "powerpc"* || $TARGET == *"android" || $TARGET = i*86-unknown-linux-gnu ]]; then
            cd $ADHAMMER_ROOT_DIR
            sed -Ei 's|^native-tls = "([^"]+)"$|native-tls = { version = "\1", features = ["vendored"] }|' crates/collector/Cargo.toml
            grep -R 'vendored' -n .
          fi
        
      - name: Run build
        run: |
          cd $ADHAMMER_ROOT_DIR

          if [[ -z "${CC_COMPILER:-}" ]]; then
            CC_COMPILER="cargo"
          fi
          
          if [[ $TARGET == "mips"* ]]; then
            $CC_COMPILER +nightly build -Z build-std=std,panic_abort -p "$ADHAMMER_BIN_NAME" --release --target $TARGET
          else
            $CC_COMPILER build -p "$ADHAMMER_BIN_NAME" --release --target $TARGET
          fi
                
      - name: List build information
        run: |
          OLD_ADHAMMER_BIN_DIR="$ADHAMMER_ROOT_DIR/target/$TARGET/release"
          OLD_ADHAMMER_BIN_PATH="$OLD_ADHAMMER_BIN_DIR/$ADHAMMER_BIN_NAME"
          ls -alh "$OLD_ADHAMMER_BIN_DIR"
          if [[ $TARGET == *-windows-* ]]; then
            OLD_ADHAMMER_BIN_PATH="$OLD_ADHAMMER_BIN_DIR/$ADHAMMER_BIN_NAME.exe"
          fi
          
          ADHAMMER_BIN_PATH="${{ runner.temp }}/$ADHAMMER_BIN_NAME-$ADHAMMER_VERSION-$TARGET"
          if [[ $OS == windows* || $TARGET == *-windows-* ]]; then
            ADHAMMER_BIN_PATH="${{ runner.temp }}/$ADHAMMER_BIN_NAME-$ADHAMMER_VERSION-$TARGET.exe"
          fi
          ADHAMMER_BIN_HASH_PATH="$ADHAMMER_BIN_PATH.sha256.txt"
          
          cp -f "$OLD_ADHAMMER_BIN_PATH" "$ADHAMMER_BIN_PATH"
          ls -alh "$ADHAMMER_BIN_PATH"

          cd "$(dirname "$ADHAMMER_BIN_PATH")"
          sha256sum --tag "$(basename "$ADHAMMER_BIN_PATH")" | tee "$ADHAMMER_BIN_HASH_PATH"
          ldd "$ADHAMMER_BIN_PATH" || true
          "$ADHAMMER_BIN_PATH" -h || true 
          
          echo "ADHAMMER_BIN_PATH=$ADHAMMER_BIN_PATH" >> $GITHUB_ENV
          echo "ADHAMMER_BIN_HASH_PATH=$ADHAMMER_BIN_HASH_PATH" >> $GITHUB_ENV
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.TARGET }}
          path: |
            ${{ env.ADHAMMER_BIN_PATH }}
            ${{ env.ADHAMMER_BIN_HASH_PATH }}

  deploy_release:
    needs: [checkout, build]
    runs-on: ubuntu-latest
    env:
       ADHAMMER_CURRENT_COMMIT_ID: ${{ needs.checkout.outputs.ADHAMMER_CURRENT_COMMIT_ID }}
       ADHAMMER_VERSION: ${{ needs.checkout.outputs.ADHAMMER_VERSION }}
    
    steps:
     - name: Download Artifact
       uses: actions/download-artifact@v8
       with:
        pattern: binary-*
        merge-multiple: true
        path: /tmp/results

     - name: List target
       run: |
          cd "/tmp/results"
          ls -alh
  
          RELEASE_NOTES="/tmp/release_notes.txt"
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
          
          cat *.sha256.txt > "$RELEASE_NOTES"
          sha256sum -c *.sha256.txt
          
          mkdir -p "/tmp/hashes"
          mv -f *.sha256.txt "/tmp/hashes/"
  
     - name: Create a new Github release
       uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b #v3.0.1
       with:
         make_latest: true
         body_path: ${{ env.RELEASE_NOTES }}
         name: version ${{ env.ADHAMMER_VERSION }} - build ${{ env.ADHAMMER_CURRENT_COMMIT_ID }}
         tag_name: ${{ env.ADHAMMER_CURRENT_COMMIT_ID }}
         files: |
           /tmp/results/${{ env.ADHAMMER_BIN_NAME }}-*
